import { Router } from 'express';
import { z } from 'zod';
import { authenticate } from '../../middlewares/authenticate';
import { authorize } from '../../middlewares/authorize';
import { validate } from '../../middlewares/validate';
import { ADMIN_ROLES, SUPER_ADMIN } from '../../config/roles';
import * as controller from '../../controllers/notification.controller';

const router = Router();
const subscription = z.object({ endpoint: z.string().url().max(2048), keys: z.object({ p256dh: z.string().min(16).max(500), auth: z.string().min(8).max(500) }), deviceName: z.string().max(120).optional() });
const enabled = z.object({ enabled: z.boolean() });
const adminId = z.object({ adminId: z.coerce.number().int().positive() });
router.use(authenticate, authorize(...ADMIN_ROLES));
router.post('/subscriptions', validate(subscription), controller.subscribe);
router.delete('/subscriptions', validate(z.object({ endpoint: z.string().url().max(2048) })), controller.unsubscribe);
router.get('/status', controller.status);
router.get('/vapid-public-key', controller.vapidKey);
router.put('/settings', authorize(SUPER_ADMIN), validate(enabled), controller.settings);
router.get('/recipients', authorize(SUPER_ADMIN), controller.recipients);
router.put('/recipients/:adminId', authorize(SUPER_ADMIN), validate(adminId, 'params'), validate(enabled), controller.updateRecipient);
router.get('/', controller.list);
router.patch('/:id/read', controller.read);
router.post('/read-all', controller.readAll);
export default router;
